[package]
name = "nft-minter-meta"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.nft-minter]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.31.1"
